update
RafallPawlak/nodejs-homework-goit pull request #2
Opened 2023-03-23 08:08 UTC by RafallPawlak

Proszę o sprawdzenie

2023-03-23 16:34 UTC, iddux requested changes

2023-03-23 16:34 UTC, iddux commented on service/contacts.json
Nieużywany plik, proszę o usunięcie

2023-03-23 16:34 UTC, iddux commented on server.js
> + app.use('/api/contacts', contactsRouter)
Proszę o poprawe formatowania kodu

2023-03-23 16:34 UTC, iddux commented on routes/api/contacts.js
> +    const favoritetUpdate = await updateContact( id, req.body);
literówka -> `favoriteUpdate`

2023-03-23 16:34 UTC, iddux commented on routes/api/contacts.js
> +    const favoritetUpdate = await updateContact( id, req.body);
Dodatkową rzeczą jest to, że możliwe jest dodanie jakichkolwiek danych, i kontakt zostanie zaktualizowany za pomocą tych danych. Jedyną możliwością powinno być zmienienie pola `favorite`, z wyłączeniem innych pól

2023-03-23 16:34 UTC, iddux commented on routes/api/contacts.js
> +    console.log(contact);
Proszę o usunięcie tej linii kodu.

2023-03-24 21:00 UTC, RafallPawlak commented
Dzięki za sprawdzenie :) Przesyłam poprawki

2023-03-25 09:33 UTC, merged